### ISSUE TITLE
Add the posibility to change the logging verbosity

### ISSUE THREAD

**Issue by 33Fraise33** [nokia/OSSMediator#21]
Hello,

In the mediator and elasticsearch logs we notice that there are quite some logs with level=info. 
It would be handy to be able the logging level in the configuration files of both services.

**Comment by soursing** [comment]
Hi @33Fraise33,

MediatorCollector and ElasticSearchPlugin has below option to change logging lovel:
**-log_level int
    Log Level (default 4), logger level in collector.log file. Values: 0 (PANIC), 1 (FATAl), 2 (ERROR), 3 (WARNING), 4 (INFO), 5 (DEBUG)**

You can add log_level option as per your need.

If you are using Collector and ElasticSearchPlugin as service, please add log_level option to the following line:
https://github.com/nokia/OSSMediator/blob/6ee1ad408cac1c4292ea01688d2e0b3fe7506608/MediatorSetup/services_template/collector.service#L13
https://github.com/nokia/OSSMediator/blob/6ee1ad408cac1c4292ea01688d2e0b3fe7506608/MediatorSetup/services_template/elasticsearchplugin.service#L12

**Comment by 33Fraise33** [comment]
Thanks I have implemented this.
