### ISSUE TITLE
Sims folder grows super large without being cleaned up

### ISSUE THREAD

**Issue by 33Fraise33** [nokia/OSSMediator#27]
Hi,

We are running mediator version 3.1 and we notice that the sims folder for each network is growing very large. 
fmdata and pmdata is being cleared by the elasticsearch exporter but the sims folder is not being read by that exporter so the folder just keeps growing. Is it possible to disable the sims feature or having it imported into elasticsearch with an accompanied dashboard?

**Comment by soursing** [comment]
Hi, 

We'll check the sims folder cleanup issue.
You can disable the sims api by removing the api from `sims_api` section in `resources/conf.json` file.

We're working on dashboards for sim APIs, we'll update once done.
