### ISSUE TITLE
Do not run make test in docker image build

### ISSUE THREAD

**Issue by 33Fraise33** [nokia/OSSMediator#42]
Hello,

You have a line: https://github.com/nokia/OSSMediator/blob/3b253ac5743ea684853a1a7bfc8899b7a1469961/ElasticsearchPlugin/Dockerfile#L38
this makes the build take way longer than needed as each build always includes the tests. 

Es this something that is done on purpose and is this a general best practice? 
I also do not understand why you would run the builder seperately in the makefile: https://github.com/nokia/OSSMediator/blob/3b253ac5743ea684853a1a7bfc8899b7a1469961/ElasticsearchPlugin/Makefile#L13

if you are planning to run docker it does not make sense as you can just get the plugin or collector binaries like: 
`sudo docker run -it --volumes-from=ossmediator --entrypoint=/bin/sh ossmediatorcollector:latest -i`

**Comment by soursing** [comment]
Hi Gianni, Thanks for the input.

I've made the changes and added `make docker_build` process for building without test cases.

`make all` : Will run both build and test
`make docker_build`: Will only run build process

PR: https://github.com/nokia/OSSMediator/pull/40

Please check.

**Comment by 33Fraise33** [comment]
Looks good I think ;)

**Comment by soursing** [comment]
Closing the issue.
